### ISSUE TITLE
Install Problem (Python 2.7.6 on Linux 3.16.0-38-generic)

### ISSUE THREAD

**Issue by corpr8** [peter-ch/MultiNEAT#32]
Hi there, can you provide any clues for the install problem below (Python 2.7.6 on Linux 3.16.0-38-generic)? Thanks!

python setup.py build_ext
Compiling _MultiNEAT.pyx because it changed.
[1/1] Cythonizing _MultiNEAT.pyx

Error compiling Cython file:
------------------------------------------------------------
...

    def BuildESHyperNEATPhenotype(Genome self, NeuralNetwork a_net, Substrate subst, Parameters params):
        self.thisptr.BuildESHyperNEATPhenotype(deref(a_net.thisptr), deref(subst.thisptr), deref(params.thisptr))
    
    def Save(self, str a_filename):
        self.thisptr.Save(a_filename)
                        ^
------------------------------------------------------------

_MultiNEAT.pyx:927:25: no suitable method found
Traceback (most recent call last):
  File "setup.py", line 96, in <module>
    ext_modules=getExtensions())
  File "setup.py", line 71, in getExtensions
    extra_compile_args=extra)],
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 877, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python2.7/dist-packages/Cython/Build/Dependencies.py", line 997, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: _MultiNEAT.pyx

**Comment by pi1412** [comment]
I have the same problem，did  you  solve it？@corpr8

**Comment by pi1412** [comment]
@corpr8 I solved this problem by re-install Cython.
